apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticketing
build:
  googleCloudBuild:
    projectId: ticketing-dev-442717
  artifacts:
    - image: eu.gcr.io/ticketing-dev-442717/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
