apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo
  labels:
    app: auth-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo
  labels:
    app: auth-mongo
spec:
  type: ClusterIP # Change to NodePort or LoadBalancer if needed
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: auth-mongo
